### ISSUE TITLE
rresult fails to build on 4.14.0+trunk

### ISSUE THREAD

**Issue by shubhamkumar13** [dbuenzli/rresult#24]
I get the following error log when I try to build `rresult` with `4.14.0+trunk` and `dune.2.9.0`

```
#=== ERROR while compiling rresult.0.6.0 ======================================#
# context     2.0.8 | linux/x86_64 | ocaml-variants.4.14.0+trunk | https://opam.ocaml.org#1fc79772
# path        ~/.opam/4.14.0+trunk/.opam-switch/build/rresult.0.6.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --pinned false
# exit-code   1
# env-file    ~/.opam/log/rresult-2326322-d2c37b.env
# output-file ~/.opam/log/rresult-2326322-d2c37b.out
### output ###
# [...]
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/sk/.opam/4.14.0+trunk/lib/ocaml, /home/sk/.opam/4.14.0+trunk/lib/ocaml/compiler-libs
# File "src/rresult_top.ml", line 7, characters 17-33:
# 7 | let () = ignore (Toploop.use_file Format.err_formatter "rresult_top_init.ml")
#                      ^^^^^^^^^^^^^^^^
# Error: Unbound value Toploop.use_file
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/rresult.a' 'src/rresult.cmxs' 'src/rresult.cmxa'
#      'src/rresult.cma' 'src/rresult.cmx' 'src/rresult.cmi' 'src/rresult.mli'
#      'src/rresult_top.a' 'src/rresult_top.cmxs' 'src/rresult_top.cmxa'
#      'src/rresult_top.cma' 'src/rresult_top.cmx' 'src/rresult_top_init.ml']: exited with 10

```

**Comment by dbuenzli** [comment]
See https://github.com/ocaml/ocaml/issues/10556
